Capabilities:
  Application: &ApplicationCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Channel: &ChannelCapabilities
    V2_0: true

Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/supplychain.com/msp
    Policies:
      Readers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
      Endorsement:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"

  - &Manufacturer
    Name: Manufacturer
    ID: ManufacturerMSP
    MSPDir: ./crypto-config/peerOrganizations/manufacturer.supplychain.com/msp
    AnchorPeers:
      - Host: manufacturer.supplychain.com
        Port: 7051
    Policies:
      Readers:
          Type: Signature
          Rule: "OR('ManufacturerMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('ManufacturerMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('ManufacturerMSP.admin')"
      Endorsement:
          Type: Signature
          Rule: "OR('ManufacturerMSP.member')"

  - &Distributor
    Name: Distributor
    ID: DistributorMSP
    MSPDir: ./crypto-config/peerOrganizations/distributor.supplychain.com/msp
    AnchorPeers:
      - Host: distributor.supplychain.com
        Port: 7051
    Policies:
      Readers:
          Type: Signature
          Rule: "OR('DistributorMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('DistributorMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('DistributorMSP.admin')"
      Endorsement:
          Type: Signature
          Rule: "OR('DistributorMSP.member')"

  - &Retailer
    Name: Retailer
    ID: RetailerMSP
    MSPDir: ./crypto-config/peerOrganizations/retailer.supplychain.com/msp
    AnchorPeers:
      - Host: retailer.supplychain.com
        Port: 7051
    Policies:
      Readers:
          Type: Signature
          Rule: "OR('RetailerMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('RetailerMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('RetailerMSP.admin')"
      Endorsement:
          Type: Signature
          Rule: "OR('RetailerMSP.member')"

Orderer: &OrdererDefaults

  OrdererType: solo

  Addresses:
    - orderer.supplychain.com:7050

  Capabilities:
    <<: *OrdererCapabilities

  Policies:
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        Rule: "ANY Admins"

    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

  BatchTimeout: 2s

  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

Application: &ApplicationDefaults
  Policies:

    LifecycleEndorsement:
        Type: ImplicitMeta
        Rule: "ANY Endorsement"

    Endorsement:
        Type: ImplicitMeta
        Rule: "ANY Endorsement"
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        Rule: "ANY Admins"

  Organizations:
    - <<: *Manufacturer
    - <<: *Distributor
    - <<: *Retailer
  
  Capabilities:
    <<: *ApplicationCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        Rule: "ANY Admins"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  SupplyChainOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *Orderer
    Consortiums:
      SupplyChainConsortium:
        Organizations:
          - *Manufacturer
          - *Distributor
          - *Retailer
    Application:
      <<: *ApplicationDefaults

      Organizations:
        - *Manufacturer
        - *Distributor
        - *Retailer

  SupplyChainChannel:
    <<: *ChannelDefaults
    Consortium: SupplyChainConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Manufacturer
        - *Distributor
        - *Retailer
