OrdererOrgs:
  - Name: OrdererOrg
    Domain: supplychain.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Manufacturer
    Domain: manufacturer.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Distributor
    Domain: distributor.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Retailer
    Domain: retailer.supplychain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
