services:
  monitoring_system_api_database:
    container_name: monitoring_system_api_database
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    user: postgres
    volumes:
      - monitoring_system_api_database_volume:/var/lib/postgresql/data
    env_file:
      - envs/api-database.env
    networks:
      - monitoring_system_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "apidb"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  monitoring_system_api_database_volume:
    name: monitoring_system_api_database_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/postgres/data