services:
  fabric-tools:
    image: hyperledger/fabric-tools:latest
    container_name: fabric-tools
    tty: true
    stdin_open: true
    volumes:
      - ./hyperledger-fabric:/etc/hyperledger/fabric/
    working_dir: /etc/hyperledger/fabric
